### ISSUE TITLE
What is "EGYBEST_MIRROR"

### ISSUE THREAD

**Issue by user45786** [SafwanLjd/EgyBestTeleBot#3]
I'm reading the code and it's absolutely amazing and helpful tool.
but I've got a question.

"EGYBEST_MIRROR" ? what is it ?
canyou provide an example.
thanks alot.

**Comment by SafwanLjd** [comment]
EgyBest is a website that has many mirrors, AKA the same site is hosted under multiple domains, a "mirror" refers to a domain that hosts an instance of EgyBest…

You can visit `https://egy.best` which will automatically redirect you to one of the mirrors, which I'd recommend setting the variable to, because most mirrors go down after some time and get replaced by new ones

**Comment by user45786** [comment]
thanks for responding 💬
I've tried to EGYBEST_MIRROR value on heroku vars to :
https://gero.egybest.ski

the bot can't find any movies/shows.
will always answer:   لم أستطع العثور على بحثك في إيجي بيست❗

**Comment by SafwanLjd** [comment]
The server must not be located in the US, EgyBest blocks all requests that come from a US IP address

**Comment by user45786** [comment]
that's true. 
can i rotate the traffic before sending the request in heroku ? 
what server provider are u using?

**Comment by SafwanLjd** [comment]
Heroku provides the option to use a Europe based server when you create a new "Heroku app"

**Comment by user45786** [comment]
so i need to create a new app ? can i change it for the app I've created? I'm new to heroku sorry.
thanks again for responding ❤️
so egybest is working in Europe ?!.. that's interesting..

**Comment by SafwanLjd** [comment]
As far as I'm aware yes you do have to create a new app, it's been a while since I used Heroku but I don't remember that changing the region was an option.

And yes, EgyBest does work in Europe.

For help with Heroku related questions you can read their documention or ask for help in any Heroku related forum.

**Comment by user45786** [comment]
thanks alot I'll try it out.
you are completely right i should read the docs and i will.
ur repos are amazing.. i wish that y'll continue developing them.

**Comment by SafwanLjd** [comment]
You're welcome, most of my repos are honestly neglected messy projects that I started just because I felt like it, this one not being any different… I just open source them because I like open source software and so that someone somewhere sometime might dig through the code and make something worthy out of it
